const BOOKING_STATUS = {
  PENDING_MATCH: 'PENDING_MATCH',
  ASSIGNED: 'ASSIGNED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};

const ALLOWED_BOOKING_STATUS = new Set(Object.values(BOOKING_STATUS));

module.exports = { BOOKING_STATUS, ALLOWED_BOOKING_STATUS };
